name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker build . --file Dockerfile --tag f5star/openapi-url-watcher:latest
            docker push f5star/openapi-url-watcher:latest
